// <auto-generated />
using System;
using DuAn1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DuAn1.Migrations
{
    [DbContext(typeof(Duan1Context))]
    [Migration("20250707020242_duan1")]
    partial class duan1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DuAn1.Models.ChiTietKhuyenMai", b =>
                {
                    b.Property<string>("MaKhuyenMai")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaSanPham")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaKhuyenMai", "MaSanPham")
                        .HasName("PK__ChiTietK__A0FAC7FF18C39CDD");

                    b.HasIndex("MaSanPham");

                    b.ToTable("ChiTietKhuyenMai", (string)null);
                });

            modelBuilder.Entity("DuAn1.Models.GioHang", b =>
                {
                    b.Property<string>("MaGioHang")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaKhachHang")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("NgayThem")
                        .HasColumnType("datetime");

                    b.Property<int?>("SoLoaiSanPham")
                        .HasColumnType("int");

                    b.HasKey("MaGioHang")
                        .HasName("PK__GioHang__F5001DA316F5CBA4");

                    b.HasIndex(new[] { "MaKhachHang" }, "UQ__GioHang__88D2F0E406D6BABF")
                        .IsUnique()
                        .HasFilter("[MaKhachHang] IS NOT NULL");

                    b.ToTable("GioHang", (string)null);
                });

            modelBuilder.Entity("DuAn1.Models.Hang", b =>
                {
                    b.Property<string>("MaHang")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenHang")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TinhNang")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaHang")
                        .HasName("PK__Hang__19C0DB1DF8E2C2A8");

                    b.ToTable("Hang", (string)null);
                });

            modelBuilder.Entity("DuAn1.Models.HoaDon", b =>
                {
                    b.Property<string>("MaHoaDon")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaGioHang")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaKhachHang")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("NgaySuaChua")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHoaDon")
                        .HasName("PK__HoaDon__835ED13B1892C1EB");

                    b.HasIndex("MaGioHang");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("DuAn1.Models.HoaDonChiTiet", b =>
                {
                    b.Property<string>("MaHoaDon")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaSanPham")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaHoaDon", "MaSanPham")
                        .HasName("PK__HoaDonCh__4CF2A579A6E9C74D");

                    b.HasIndex("MaSanPham");

                    b.ToTable("HoaDonChiTiet", (string)null);
                });

            modelBuilder.Entity("DuAn1.Models.KhachHang", b =>
                {
                    b.Property<string>("MaKhachHang")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SDT");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaKhachHang")
                        .HasName("PK__KhachHan__88D2F0E5A0D6A4C0");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("DuAn1.Models.KhuyenMai", b =>
                {
                    b.Property<string>("MaKhuyenMai")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaQuanLy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("PhanTramGiam")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("TenKhuyenMai")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaKhuyenMai")
                        .HasName("PK__KhuyenMa__6F56B3BD6B7817BE");

                    b.HasIndex("MaQuanLy");

                    b.ToTable("KhuyenMai", (string)null);
                });

            modelBuilder.Entity("DuAn1.Models.MauSac", b =>
                {
                    b.Property<string>("MaMauSac")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenMauSac")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaMauSac")
                        .HasName("PK__MauSac__B9A911624FF7023E");

                    b.ToTable("MauSac", (string)null);
                });

            modelBuilder.Entity("DuAn1.Models.QuanLy", b =>
                {
                    b.Property<string>("MaQuanLy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenQuanLy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaQuanLy")
                        .HasName("PK__QuanLy__2AB9EAF8F4C5CFE8");

                    b.ToTable("QuanLy", (string)null);
                });

            modelBuilder.Entity("DuAn1.Models.SanPham", b =>
                {
                    b.Property<string>("MaSanPham")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("DungLuongPin")
                        .HasColumnType("int");

                    b.Property<string>("HinhMinhHoa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("KhoangCachKetNoi")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("KichCo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KieuKetNoi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LanSuaGanNhat")
                        .HasColumnType("datetime");

                    b.Property<string>("MaHang")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaKhuyenMai")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaMauSac")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("SoLuongTonKho")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaSanPham")
                        .HasName("PK__SanPham__FAC7442D116B707B");

                    b.HasIndex("MaHang");

                    b.HasIndex("MaKhuyenMai");

                    b.HasIndex("MaMauSac");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("DuAn1.Models.SanPhamGioHang", b =>
                {
                    b.Property<string>("MaGioHang")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaSanPham")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaGioHang", "MaSanPham")
                        .HasName("PK__SanPhamG__3AAC69E1A4D8FB38");

                    b.HasIndex("MaSanPham");

                    b.ToTable("SanPhamGioHang", (string)null);
                });

            modelBuilder.Entity("DuAn1.Models.ChiTietKhuyenMai", b =>
                {
                    b.HasOne("DuAn1.Models.KhuyenMai", "MaKhuyenMaiNavigation")
                        .WithMany("ChiTietKhuyenMais")
                        .HasForeignKey("MaKhuyenMai")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietKh__MaKhu__619B8048");

                    b.HasOne("DuAn1.Models.SanPham", "MaSanPhamNavigation")
                        .WithMany("ChiTietKhuyenMais")
                        .HasForeignKey("MaSanPham")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietKh__MaSan__628FA481");

                    b.Navigation("MaKhuyenMaiNavigation");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("DuAn1.Models.GioHang", b =>
                {
                    b.HasOne("DuAn1.Models.KhachHang", "MaKhachHangNavigation")
                        .WithOne("GioHang")
                        .HasForeignKey("DuAn1.Models.GioHang", "MaKhachHang")
                        .HasConstraintName("FK__GioHang__MaKhach__66603565");

                    b.Navigation("MaKhachHangNavigation");
                });

            modelBuilder.Entity("DuAn1.Models.HoaDon", b =>
                {
                    b.HasOne("DuAn1.Models.GioHang", "MaGioHangNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaGioHang")
                        .HasConstraintName("FK__HoaDon__MaGioHan__6A30C649");

                    b.HasOne("DuAn1.Models.KhachHang", "MaKhachHangNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKhachHang")
                        .HasConstraintName("FK__HoaDon__MaKhachH__6B24EA82");

                    b.Navigation("MaGioHangNavigation");

                    b.Navigation("MaKhachHangNavigation");
                });

            modelBuilder.Entity("DuAn1.Models.HoaDonChiTiet", b =>
                {
                    b.HasOne("DuAn1.Models.HoaDon", "MaHoaDonNavigation")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("MaHoaDon")
                        .IsRequired()
                        .HasConstraintName("FK__HoaDonChi__MaHoa__71D1E811");

                    b.HasOne("DuAn1.Models.SanPham", "MaSanPhamNavigation")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("MaSanPham")
                        .IsRequired()
                        .HasConstraintName("FK__HoaDonChi__MaSan__72C60C4A");

                    b.Navigation("MaHoaDonNavigation");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("DuAn1.Models.KhuyenMai", b =>
                {
                    b.HasOne("DuAn1.Models.QuanLy", "MaQuanLyNavigation")
                        .WithMany("KhuyenMais")
                        .HasForeignKey("MaQuanLy")
                        .HasConstraintName("FK__KhuyenMai__MaQua__52593CB8");

                    b.Navigation("MaQuanLyNavigation");
                });

            modelBuilder.Entity("DuAn1.Models.SanPham", b =>
                {
                    b.HasOne("DuAn1.Models.Hang", "MaHangNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaHang")
                        .HasConstraintName("FK__SanPham__MaHang__5CD6CB2B");

                    b.HasOne("DuAn1.Models.KhuyenMai", "MaKhuyenMaiNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaKhuyenMai")
                        .HasConstraintName("FK__SanPham__MaKhuye__5DCAEF64");

                    b.HasOne("DuAn1.Models.MauSac", "MaMauSacNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaMauSac")
                        .HasConstraintName("FK__SanPham__MaMauSa__5BE2A6F2");

                    b.Navigation("MaHangNavigation");

                    b.Navigation("MaKhuyenMaiNavigation");

                    b.Navigation("MaMauSacNavigation");
                });

            modelBuilder.Entity("DuAn1.Models.SanPhamGioHang", b =>
                {
                    b.HasOne("DuAn1.Models.GioHang", "MaGioHangNavigation")
                        .WithMany("SanPhamGioHangs")
                        .HasForeignKey("MaGioHang")
                        .IsRequired()
                        .HasConstraintName("FK__SanPhamGi__MaGio__6E01572D");

                    b.HasOne("DuAn1.Models.SanPham", "MaSanPhamNavigation")
                        .WithMany("SanPhamGioHangs")
                        .HasForeignKey("MaSanPham")
                        .IsRequired()
                        .HasConstraintName("FK__SanPhamGi__MaSan__6EF57B66");

                    b.Navigation("MaGioHangNavigation");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("DuAn1.Models.GioHang", b =>
                {
                    b.Navigation("HoaDons");

                    b.Navigation("SanPhamGioHangs");
                });

            modelBuilder.Entity("DuAn1.Models.Hang", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("DuAn1.Models.HoaDon", b =>
                {
                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("DuAn1.Models.KhachHang", b =>
                {
                    b.Navigation("GioHang");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("DuAn1.Models.KhuyenMai", b =>
                {
                    b.Navigation("ChiTietKhuyenMais");

                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("DuAn1.Models.MauSac", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("DuAn1.Models.QuanLy", b =>
                {
                    b.Navigation("KhuyenMais");
                });

            modelBuilder.Entity("DuAn1.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietKhuyenMais");

                    b.Navigation("HoaDonChiTiets");

                    b.Navigation("SanPhamGioHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
